### ISSUE TITLE
overlapping midnight with ph and semicolons

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#145]
Similar to https://github.com/opening-hours/opening_hours.js/issues/87 
I think they have to be an warning or "other warning" for overwriting midnight-overlapping taggings especially if it contains PH. There is 2 of 100 Taggings right in the DB.
Like
Mo-Su 09:00-01:00; PH 08:00-02:00
similar (and more difficult to detect) problem without semicolon:
Mo-Su 08:00-02:00, PH 09:00-01:00

And the idea a little bit more harder: should there not better be an warning for all overlapping midnight-ranges, wat is overwritten by Semicolon? (And maybe a more softer warning for Comma) 
Have found 5 or 10 (ok, maybe 20) right taggings in 1000 OH-Pois in the last days ... oO

**Comment by ypid** [comment]
Sound good and should not be too difficult.

**Comment by ypid** [comment]
Implemented in #220.

**Comment by ypid** [comment]
> Mo-Su 08:00-02:00, PH 09:00-01:00

@dex2000 That is really difficult to detect and I did currently not try it. Because [Mo-Su 08:00-01:00, PH 06:00-03:00](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Su%2008%3A00-01%3A00%2C%20PH%2006%3A00-03%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1483723020000) would be perfectly valid. The checking is generally not done on the tokens (e. g. the internal representation of `Mo-Su 08:00-02:00, PH 09:00-01:00`) but instead done more abstractly by asking if the first rule contains a weekday selector and the following is an additional rule and so on. If you can come up with such a definition which should ideally not match any false positives I can implement it.
I can not even "run each rule against the other" and see if they would overwrite each other in a time range in say 5 years which would be an acceptable check. The only problem here is that the `01:00-02:00` portion of the first rule still evaluates to open when the second one matches.

> And the idea a little bit more harder: should there not better be an warning for all overlapping midnight-ranges, wat is overwritten by Semicolon? (And maybe a more softer warning for Comma)

I don’t think that would be a good idea because of false positives. I also tried to avoid false positives when implementing this. The check is very narrow. For example, the check is not fullish enough to emit a false positive for [2017 Mo-Su 09:00-01:00; 2023 PH 08:00-12:00](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Sa%2011%3A00-22%3A00%3B%20Su%2CPH%2012%3A00-22%3A00&lat=50.7377077&lon=7.1024651) (because the check is not run if both checked rules are too complex).

**Comment by dex2000** [comment]
Ok.
