### ISSUE TITLE
http://openingh.openstreetmap.de/evaluation_tool/ is not working right now

### ISSUE THREAD

**Issue by nathanv** [opening-hours/opening_hours.js#169]
http://openingh.openstreetmap.de/evaluation_tool/ doesn't load

**Comment by ypid** [comment]
Hm, that is bad. Also because the mirror is currently down. https://github.com/opening-hours/opening_hours_map/issues/43

http://openingh.openstreetmap.de/evaluation_tool/
sometimes has a higher response time. It seems to work again now. Sorry for the inconvenience.

**Comment by dex2000** [comment]
Don't works again ...

**Comment by ypid** [comment]
Working on it :wink: I am solving #172 in one go and messing a bit with @debops and LXC and so on. I adapted the map yesterday to make it work over HTTPS.

**Comment by ypid** [comment]
Should be live: https://openingh.ypid.de/
Feel free to report any issues. I configured redirects for the old http://ypid.de/~osm setup.
Furthermore I am going to contact the admin of http://openingh.openstreetmap.de/ so that this domain could point to my server using a CNAME to openingh.ptr.ypid.de after a bit of testing of the new setup. Then I can host that domain and also issue a X.509 cert by Let's Encrypt.

**Comment by ypid** [comment]
Should work now. The server has been re-installed in the past and I am not aware of issues currently.
