### ISSUE TITLE
Host online tool on GitHub Pages or use HTTPS for own server

### ISSUE THREAD

**Issue by rugk** [opening-hours/opening_hours.js#172]
Could you please host http://openingh.openstreetmap.de/evaluation_tool/ on GitHub Pages (which [provides HTTPS](https://github.com/blog/2186-https-for-github-pages)) or at least use HTTPS on your own page?

**Comment by ypid** [comment]
I was waiting for someone to request HTTPS :wink: and I am planing on doing this together with the map. I already tried that once and then realized that there needs to be a bit of adjustment because this projects works with the external services Nominatim and the Overpass API and something broke there. However, I am not yet sure when openingh.openstreetmap.de can be switched to HTTPS because that server is not under my full control. But I should be able to get my mirror up and running and then properly redirect from legacy HTTP to HTTPS.

**Comment by ypid** [comment]
Should be live: https://openingh.ypid.de/
Feel free to report any issues.

**Comment by rugk** [comment]
Awesome, I tested it a bit and everything is working!

**Comment by ypid** [comment]
Mirror is up and running. What is remaining is the main domain openingh.openstreetmap.de. Tracked in #203. Closing this issue.
