### ISSUE TITLE
check for comma as last letter

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#186]
not really an error:
_Su 10:00-16:00,_
but should give a warning or "other warning"

P.s. Jaja, es ist mal wieder Monatsanfang ;)

**Comment by ypid** [comment]
I guess before you submit a warning request for every little detail that the evaluation tool already knows is not "the prefect opening_hours style" we should discuss if the pretty opening_hours value could be used for this? The problem is that a warning for every oh value which is not prettified would give you 100 000 objects (ref: [stats](http://openingh.openstreetmap.de/stats/)) …

Any idea where to draw the line?

**Comment by dex2000** [comment]
vote for prettify because it's not really an error

**Comment by ypid** [comment]
ok. I thought this should already be handled by the prettify function. Seems it does not yet. Needs to be fixed. Thanks.

**Comment by ypid** [comment]
#220 adds this warning. I should have acknowledged this as enhancement in a earlier release as values ending with `;` already/also trigger a warning.
