### ISSUE TITLE
OT: compare 2 rules

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#197]
Have tried to compact/prettify a rule, but evaluation-tool says no:

    Jan-Mar: Mo-Fr 10:00-17:00, Jan-Mar Sa 10:00-14:00, Jan-Mar Su,PH off; 
    Apr,Nov-Dec: Mo-Fr 10:00-18:00, Apr,Nov-Dec: Sa 10:00-14:00, Apr,Nov-Dec: Su,PH off; 
    May-Oct: Mo-Fr 10:00-18:00, May-Oct:Sa 10:00-15:00, May-Oct:Su,PH 10:00-14:00; 
    Dec 24-26,Dec 31,Jan 01,Jan 06,2017 Jan 10 off

compacted to:

    Sa 10:00-14:00; 
    Jan-Mar: Mo-Fr 10:00-17:00; 
    Apr-Dec: Mo-Fr 10:00-18:00; 
    Su,PH off; 
    May-Oct: Sa 10:00-15:00, May-Oct Su,PH 10:00-14:00; 
    Dec 24-26,Dec 31,Jan 01,Jan 06,2017 Jan 10 off

Where is my mistake?

**Comment by ypid** [comment]
The problem appears to be the overuse of the [`<additional_rule_separator>`](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator) token (example `, May-Oct Su,PH 10:00-14:00` which caused this rule to become additive). I started by rewrtting your first example into this:

    Jan-Mar: Mo-Fr 10:00-17:00; Jan-Apr,Nov-Dec: Sa 10:00-14:00;
    Apr-Dec: Mo-Fr 10:00-18:00;
    May-Oct: Sa 10:00-15:00; PH off; May-Oct: Su,PH 10:00-14:00;
    Dec 24-26,Dec 31,Jan 01,Jan 06,2017 Jan 10 off

And the second one into this:

    Jan-Mar: Mo-Fr 10:00-17:00;
    Apr-Dec: Mo-Fr 10:00-18:00;
    Sa 10:00-14:00;
    Su,PH off;
    May-Oct: Sa 10:00-15:00; May-Oct Su,PH 10:00-14:00;
    Dec 24-26,Dec 31,Jan 01,Jan 06,2017 Jan 10 off

Which now passes the comparison. If it does not pass, the tool will tell you why it does not pass and where the first derivation is.

If you now ask which version to prefer: I would prefer the second version because it contains less redundancy and is easier to read. Remember to let the tool prettify the value to remove the newlines.

**Comment by dex2000** [comment]
Looks nice, thx.
