### ISSUE TITLE
Poorly handled incorrect value

### ISSUE THREAD

**Issue by maxerickson** [opening-hours/opening_hours.js#209]
Noted it by accident, the JOSM validator didn't raise any warnings.

"Monday - Friday: 8:30 AM-5:30PM, Saturday: 9AM-1PM" from v1 of https://www.openstreetmap.org/way/422234085 

In Firefox, http://openingh.openstreetmap.de/evaluation_tool/ is throwing "TypeError: tokens[nrule] is undefined".

Seems to be the combination of the erroneous colon and the comma rule combiner:

"Mo 8:30-17:30, Sa: 9:00-13:00"

**Comment by ypid** [comment]
Thanks very much for reporting. The bug is indeed in this library and is already tracked https://github.com/opening-hours/opening_hours.js/issues/86 I therefore close this issue.

I reported this issue against JOSM (https://josm.openstreetmap.de/ticket/14428) so that the exception can be caught in the meantime so that the validation can show a warning until this gets fixed here.
