### ISSUE TITLE
josm validator: appointment syntax in opening_hours

### ISSUE THREAD

**Issue by Klumbumbus** [opening-hours/opening_hours.js#210]
This is a copy of https://josm.openstreetmap.de/ticket/14392 reported by user @dieterdreist

-----

 The validator gives this warning:
(Please use notation ""on appointment"" for "by_appointment", but quotation marks aren't documented in the wiki, neither is "on appointment". The only example for appointments is "by appointment": ​https://wiki.openstreetmap.org/wiki/Key:opening_hours

Interestingly there seems to be another inconsistency, because after I added quotation marks the warning disappeared (i.e. by appointment rather than on appointment was accepted).

There is not much usage of these values anyway, but the "by appointment" has clearly more than the "on appointment": ​https://taginfo.openstreetmap.org/search?q=appointment#values

There is also a longer discussion here:
​https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours

I find it strange to use quotation marks in a formalized value, we do this nowhere else, and JOSM shouldn't recommend it. Why not by_appointment?

**Comment by ypid** [comment]
> but quotation marks aren't documented in the wiki, neither is "on appointment".

They are, see [comment](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#comment).

> neither is "on appointment

True. I guess back when I add this suggestion I wanted to kind of come up with one default comment for such cases. Probably not necessary. #211 changes that back so that the variant used originally is preserved but transformed into a comment because using `by_appointment` as a raw keyword in the language is not specified either and would break any other implementation (without the error tolerance of opening_hours.js).

> Interestingly there seems to be another inconsistency, because after I added quotation marks the warning disappeared (i.e. by appointment rather than on appointment was accepted).

Comments are free text fields.

> There is also a longer discussion here

I am very aware of this :wink:

> Why not by_appointment?

Write a proposal. I don’t think it is really necessary.

@dieterdreist Can you check #211 and see if it fixes the issue?

**Comment by dieterdreist** [comment]
2017-03-02 20:00 GMT+01:00 Robin Schneider <notifications@github.com>:

> They are, see comment
> <https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#comment>
> .
>
> neither is "on appointment
>
> True. I guess back when I add this suggestion I wanted to kind of come up
> with one default comment for such cases. Probably not necessary. #211
> <https://github.com/opening-hours/opening_hours.js/pull/211> changes that
> back so that the variant used originally is preserved but transformed into
> a comment because using by_appointment as a raw keyword in the language
> is not specified either and would break any other implementation (without
> the error tolerance of opening_hours.js).
>


OK, sorry, I must have overlooked this. There is even the hint: "The
language should be the native language of the region to which the opening
hours apply. " so this is basically something (if it is generally agreed
on) the validator can hardly ever suggest correctly.

Interestingly there seems to be another inconsistency, because after I
> added quotation marks the warning disappeared (i.e. by appointment rather
> than on appointment was accepted).
>
> Comments are free text fields.
>


right, if this comment is intended to be presented to the user ("local
language") it seems also a good choice to require quotation marks...


<https://github.com/dieterdreist>

> @dieterdreist <https://github.com/dieterdreist> Can you check #211
> <https://github.com/opening-hours/opening_hours.js/pull/211> and see if
> it fixes the issue?
>


I wish I could ;-) Had a look on it and it seems it could fix it.

**Comment by ypid** [comment]
> > Can you check #211 and see if it fixes the issue?
>
> I wish I could ;-) Had a look on it and it seems it could fix it.

Don’t worry and thanks for checking back. in #211 there is [a changelog entry](https://github.com/opening-hours/opening_hours.js/pull/211/files#diff-de0a9b67ffe2874a076b5fdb15bad484R116) which describes the intended effect. OK, I will merge this later today. It might take a while until this fix makes it into a JSOM release. I would like to make a proper release first here now with the change to rollup. Stay tuned.
