### ISSUE TITLE
Day overlap error not detected

### ISSUE THREAD

**Issue by stoecker** [opening-hours/opening_hours.js#245]
In JOSM ticket https://josm.openstreetmap.de/ticket/15582
we have a value of "opening_hours=Th 00:00-02:30,18:15-02:30". The last time format is invalid. It should either be Th 00:00-02:30,18:15-24:00 or Th 00:00-02:30,18:15-24:00;Fr 00:00-02:30 (probably the second is meant).

This is not correctly detected.

**Comment by ypid** [comment]
> This is not correctly detected.

According to the [spec](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#extended_time) and common practices in OSM, this value is valid and is functionally equal to `Th 00:00-02:30,18:15-24:00;Fr 00:00-02:30`. The only thing which makes this look wired is that `02:30` is used twice and refers to different days. Consider the two time spans on their own: `Th 00:00-02:30` and `Th 18:15-02:30`. Completely harmless on their own. Combined, they are still harmless :)

You could write it as `Th 00:00-02:30,18:15-26:30`, which is also valid. I would not recommend this. Seems wired which is why I don’t like it.
