### ISSUE TITLE
Tagging bounded opening hours

### ISSUE THREAD

**Issue by pietervdvn** [opening-hours/opening_hours.js#264]
I'm trying to tag a petting zoo which is opened "from sunset till sunrise, bounded by 08:00-22:00". So if sunrise is before 08:00, they only open at 08:00.

Neither `sunset-sunrise off; 08:00-22:00` or `sunset-sunrise, 080:00-22:00` worked. It seems as if this is missing either in the tool or in the spec.

Any idea how this should be handled?

**Comment by ypid** [comment]
It can be expressed as: `sunrise-sunset; 22:00-08:00 off`. This is also what I would prefer because I think it represents the minding well. Open from sunrise until sunset but not in the time range from 22:00-08:00.

`sunset-sunrise off; 08:00-22:00` does not work because later rules overwrite previous once.

`sunset-sunrise, 080:00-22:00` does not work because time selectors are additive.

**Comment by ypid** [comment]
Using `sunrise-sunset` with the default rule modifier "open" also helps when defining complexer opening hours like this: `Apr-Aug Mo-Fr sunrise-sunset; PH off; 22:00-08:00 off`

**Comment by pietervdvn** [comment]
Thanks! `sunrise-sunset open; 22:00-08:00 off` works correctly.


Met vriendelijke groeten,
Pieter Vander Vennet

2018-06-24 12:46 GMT+02:00 Robin Schneider <notifications@github.com>:

**Comment by ypid** [comment]
Using the `open` rule modifier is optional as it is the default state. It is needed with comments. In your case you could avoid the `open`.
