### ISSUE TITLE
site http://openingh.openstreetmap.de/evaluation_tool/ not working 08 Jan 2019

### ISSUE THREAD

**Issue by Jakkajakka** [opening-hours/opening_hours.js#279]

**Comment by Jakkajakka** [comment]
site http://openingh.openstreetmap.de/evaluation_tool/ not working 08 Jan 2019

**Comment by ypid** [comment]
"This time I backed the machine up myself :) :(" Changed insider reference to the email of the server admin of openingh.openstreetmap.de.

Thanks for reporting. I restored the my applications/services on openingh.openstreetmap.de now myself. The outage was not caused by me. I don’t blame anyone. "It can only be attributable to human error" as HAL 9000 would say.

There is also a mirror https://openingh.ypid.de/ which is under my administrative control down until and including the guest OS (Debian). Anyway.

Happy mapping.
