### ISSUE TITLE
Question for sintax

### ISSUE THREAD

**Issue by damjang** [opening-hours/opening_hours.js#286]
I have a question on how I can write this without errors:

Mo,Fr 10:00-13:00, Tu 09:00-13:00, We 15:00-17:00, Th 13:00-17:00; Mar Su[-1]-Oct Su[-1]: Mo,Fr 10:00-13:00, Tu 09:00-13:00, We,Th 15:00-18:00; PH off

but the second part (Mar Su[-1]-Oct Su[-1]: Mo,Fr 10:00-13:00, Tu 09:00-13:00, We,Th 15:00-18:00;) should be threat as grouped.

Thank you

**Comment by ypid** [comment]
As mentioned in [ToDo in the README](https://github.com/opening-hours/opening_hours.js#todo), there is no support for this in the syntax.

In your case, it does not matter because your oh value can be simplified into this where you don’t need the grouping anymore:

```
Mo,Fr 10:00-13:00, Tu 09:00-13:00, We 15:00-17:00, Th 13:00-17:00; Mar Su[-1]-Oct Su[-1]: We,Th 15:00-18:00; PH off
```

In case this would not work you would need to repeat the month selector:

```
Mo,Fr 10:00-13:00, Tu 09:00-13:00, We 15:00-17:00, Th 13:00-17:00; Mar Su[-1]-Oct Su[-1]: We,Th 15:00-18:00, Mar Su[-1]-Oct Su[-1]: Tu 09:00-12:00; PH off
```

Feel free to close the issue if that answers your question.

**Comment by damjang** [comment]
Thank you! So where needed the correct syntax is to use month selector for every sub-group.
