### ISSUE TITLE
False negative when no commas

### ISSUE THREAD

**Issue by HubMiner** [opening-hours/opening_hours.js#290]
Following example should be highlighted as error: rulesets need to be separated.
Mo-Fr 07:00-18:30 Sat 08:00-18:00

**Comment by dex2000** [comment]
In which application you get not an error/warning?

i.E. https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2007%3A00-18%3A30%20Sat%2008%3A00-18%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1559852040000 works as expected.

**Comment by HubMiner** [comment]
I was referring to this site.  The message seems to presented as warning.  I was concentrating on the time chart and the fact that it is not correct. I assumed that errors do not show chart nor prettified value.
Thanks!

**Comment by ypid** [comment]
Thanks @dex2000 @HubMiner Does that answer your question? If so you could close this issue ;-)

**Comment by HubMiner** [comment]
I'll try one more time. :)
Mainly because of PH, the validator always shows warnings which are easy to ignore.  If prettified value and graph are shown, I assume the rules are parsed successfully.  In this case missing comma is a real error since the value is not parsed correctly.  Example: Mo-Fr 07:00-18:30 Sat 08:00-21:00

**Comment by ypid** [comment]
Well, the evaluation tool has something I call input tolerance where the syntax is not strictly enforced. I have not implemented a severity for warnings so there are just errors (failed to parse) and warnings (parsed with issues). Both PH missing and missing comma are warnings because we can still interpret the value and thus run more validation on it to help the user fix all errors in one go.

I guess your request goes into the direction of adding a severity where missing comma is more severe and the missing PH can "easily be ignored"? I am not sure I would follow you in your argumentation because I of course think that missing PH should also be fixed.

Or are you suggesting to highlight warnings more in the evaluation tool? Editors like JOSM probably have better UI then the evaluation tool which is maintained by me who is not usually working on UI design ;-)

Changing the comma missing warning to an error is something I am hesitant with as explained above. I think we should rather address your issue on a UI level than on an API level (also used by JOSM) of the library.

**Comment by ypid** [comment]
@HubMiner Please test https://openingh.openstreetmap.de/evaluation_tool/ where I deployed #291 for testing.

**Comment by HubMiner** [comment]
I saw the new yellow color highlight for warnings. Since warning is always shown when there is no PH, this probably becomes yet another thing to ignore. 

Can "missing PH" be an optional check?

**Comment by ypid** [comment]
> Can "missing PH" be an optional check?

I don’t like that. This check is there for a reason. The mapper needs to clarify if the amenity is open on PH or not or what the situation is.

> I saw the new yellow color highlight for warnings.

Does it solve this issue? If so feel free to close the issue ;-)

**Comment by HubMiner** [comment]
My main argument for dropping PH warnings:
Majority of the businesses don't publish PH schedule either in store or their websites.  This results in the current state where the tool reports warnings for the majority of OH values, with no clear course to address this.

Other possible approaches: 
- Could we have different severities of warnings, with PH being cosmetic?  
- Or can the tool separate PH issue from warnings and have a dedicated reminder mentioning it, may be something below warnings box?  This would be more of a reminder (especially helpful for new users) and not a warning.

Thank you for reviewing this so far.  I am ready to close this issue as-is unless you are planning to make additional changes.

**Comment by ypid** [comment]
You are welcome. I opened #292 to track the severity idea and I merged #291 now.
