### ISSUE TITLE
How to specify the day before ?

### ISSUE THREAD

**Issue by pyrog** [opening-hours/opening_hours.js#339]
A casino is opened also the evening **before** public holidays.

**Comment by ypid** [comment]
This issue tracker is for one out of multiple implementations of the syntax. It is not a support forum about the syntax. There are far better places for such questions, which are also controlled/hosted by Openstreetmap people instead of direct competition like Microsoft:

https://help.openstreetmap.org
https://wiki.openstreetmap.org/

So I only give you a hint. Check:

https://openingh.openstreetmap.de/evaluation_tool

**Comment by pyrog** [comment]
Hi Robin,

Sorry to hurt you, but the help maybe is not clear enough 😉

**Comment by ypid** [comment]
Try `PH -1 day` :) https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#holiday Next time, please use the normal OSM support options :)
