### ISSUE TITLE
OH to iCalendar converter feature

### ISSUE THREAD

**Issue by JulianNacci** [opening-hours/opening_hours.js#343]
## Question : 
Are there any known way / library for converting OH rules to iCalendar syntax (when possible / achievable) https://icalendar.org/

Thanks in advance for your answer,
Julian

**Comment by ypid** [comment]
I only implemented a iCal parser to generate the German school holiday definitions (ref: https://gitlab.com/ypid/hc). I am open to such a feature. The closest we currently have as exporter is https://github.com/opening-hours/opening_hours.js/blob/master/PH_SH_exporter.js, but with limit to holidays.

**Comment by ypid** [comment]
It might be better to implement this outside of this repo/library. This repo is cluttered with scripts and stuff for historic reasons and I feel that ical support is not commonly needed with this library. If someone wrote it, please comment here to make people watching the issue aware of it.

Background: #143. If you feel otherwise, let me know.
