### ISSUE TITLE
Conflict when 'Open with comment' appears with 'off'

### ISSUE THREAD

**Issue by skylerbunny** [opening-hours/opening_hours.js#43]
Mo-Fr 07:00-19:30; Sa-Su 08:00-19:30; 19:30-21:00 open "No new laundry loads in"; Nov Th[4] off; Dec 25 off

This evaluates on http://openingh.openstreetmap.de/evaluation_tool/ , if you look at December 25, 20:25:

Facility is now closed, comment: "No new laundry loads in"
but will close today, 25 December, in 35 minutes.

Expected result would be:
Facility is now closed.

Evaluation shouldn't return a comment from an 'Open' string when the facility is ultimately closed, nor indicate that the facility 'will close soon', because it already is.

**Comment by dex2000** [comment]
Similar Problem:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%2CTu%2CTh-Sa%2015%3A00-23%3A00%20%22Warme%20K%C3%BCche%20ab%2016.00%20Uhr%22&DATE=1470231960000&lat=48.7769&lon=9.1844&mode=0

comment should not trigger "unknown"

**Comment by ypid** [comment]
@dex2000 Hm, your value is evaluated as expected. There might be a misconception. Refer to the [Rule modifiers section in the spec](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#section:rule_modifier). It means that when you use only a comments as rule modifier, the rule will evaluate to unknown be default. You would have to rewrite your value to this:

> Mo,Tu,Th-Sa 15:00-23:00 open "Warme Küche ab 16.00 Uhr"

Also note that you can express the warm kitchen in an machine readable way by using the tag "opening_hours:kitchen". Refer to [opening_hours statistics](http://openingh.openstreetmap.de/stats/) or taginfo. This would be:

> opening_hours=Mo,Tu,Th-Sa 15:00-23:00
> opening_hours:kitchen=Mo,Tu,Th-Sa 15:00-23:00

----

(German version)

@dex2000 Hm, Dein Wert wird korrekt ausgewertet. Eventuell ein kleines Missverständnis. Schau dir bitte die [Regeleigenschaften in der Spec](https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours/specification#section:rule_modifier) an. Daraus geht hervor, dass wenn nur ein Kommentar als Regeleigenschaft benutzt wird, die Regel mit Status Unbekannt ausgewertet wird. Du müsstest deinen Wert viel folgt schreiben:

> Mo,Tu,Th-Sa 15:00-23:00 open "Warme Küche ab 16.00 Uhr"

Noch ein kleiner Hinweis. Du kannst die Warme Küche auch Maschinenlesbar mit dem Tag "opening_hours:kitchen" angeben. Siehe [opening_hours statistics](http://openingh.openstreetmap.de/stats/) oder taginfo. Das wäre dann folgendes:

> opening_hours=Mo,Tu,Th-Sa 15:00-23:00
> opening_hours:kitchen=Mo,Tu,Th-Sa 15:00-23:00

----

@skylerbunny Can you [recheck](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2007%3A00-19%3A30%3B%20Sa-Su%2008%3A00-19%3A30%3B%2019%3A30-21%3A00%20open%20%22No%20new%20laundry%20loads%20in%22%3B%20Nov%20Th[4]%20off%3B%20Dec%2025%20off&DATE=1482693900000&lat=48.7769&lon=9.1844&mode=0). Seems like your problem has been fixed in the mean time. It outputs for the given time:
Facility is now closed
but will open tomorrow, 26 December, in 10 hours and 35 minutes.

**Comment by skylerbunny** [comment]
Looks good to me. On a day where closed, the output isn't referencing an open time that's been commented. Thanks!

**Comment by ypid** [comment]
I am closing then. Feel free to comment if something is unclear.
